shim.js

Shim buffer for SDK

---

src/redux_manager/base/store.ts

Remove Redux Logger in Production mode

[feature/remove-redux-logger-production] Remove Redux Logger in Production mode

---

src/components/CFastImage/index.js
src/navigation/stack/HomeTabs.tsx
src/screens/home/AddCustomTokenScreen/index.tsx
src/screens/nft/NFTDetailScreen.tsx
src/screens/nft/NFTScreen/ListItem.tsx

Remove validate token when add custom token, show loading indicator when load image

[fix] Remove validate token when add custom token, show loading indicator when load image

---

ios/CasperDash/AppDelegate.m
src/screens/nft/NFTScreen/index.tsx

- Fix title on header in NFT screen,
- Close the code using notification on iOS

[fix] fix title on header in NFT screen, close the code using notification on ios

---

App.tsx
android/app/build.gradle
android/app/src/main/java/io/casperdash/casperwallet/MainApplication.java
android/app/src/main/res/values/strings.xml
android/settings.gradle
ios/CasperDash/AppDelegate.m
ios/CasperDash/Info.plist
package.json
src/screens/home/ConfirmSendScreen/index.tsx
src/screens/home/HistoriesScreen/components/TransactionItem.tsx
src/screens/home/HistoriesScreen/index.tsx
src/screens/home/SendScreen/index.tsx
src/screens/nft/NFTScreen/index.tsx
src/utils/helpers/transaction.js

- Fix bug always redirect to CSPR histories screen after confirm.
- Remove CodePush
- Fix bug when send custom token (it should show "Unsupported Deploy").
- Fix transaction status icon Receive/Send in Histories screen.
- Fix header Login - Title  in NFT and Home.

[fix] redirect to histories screen, bug send custom token, remove codepush, transaction status icon, header title

---

ios/CasperDash/Info.plist

Fix issue bluetooth-peripheral background mode when submit app to store

[fix/fix-submit-store] Fix issue bluetooth-peripheral background mode when submit app to store

---

src/navigation/stack/HomeTabs.tsx
src/screens/authentication/WelcomeScreen/index.tsx
src/screens/authentication/data/data.tsx

[fix/remove-nft] remove NFT tab

---

ios/Podfile.lock
package.json
src/screens/authentication/create_new_wallet/components/ListItem.tsx

Fix bluetooth state issue when select option Connect Ledger 

[fix/bluetooth-state] fix get bluetooth state

---

README.md

Link user guide

---

ios/CasperDash/AppDelegate.m

[fix/remove-comment] remove unnecessary comments

---

src/screens/staking/StakingScreen/index.tsx

Fix keyboard auto dismiss when change amount

[fix/staking] fix keyboard auto dismiss when change amount

---

index.js
ios/CasperDash.xcodeproj/project.pbxproj
ios/Podfile.lock
package.json
shim-legacy.js
shim.js
yarn.lock

Polyfill for casper-storage
-   [x] My code has covered these test cases (please list down your tested cases):

Polyfill for casper-storage

---

src/screens/authentication/WelcomeScreen/IntroItem.tsx
src/screens/authentication/choose_pin/ChoosePinScreen/index.tsx
src/screens/authentication/choose_pin/ConfirmPinScreen/index.tsx
src/screens/authentication/create_new_wallet/DoubleCheckItScreen/index.tsx
src/screens/authentication/create_new_wallet/RecoveryPhraseScreen/index.tsx
src/screens/authentication/create_new_wallet/components/DropdownItem.tsx
src/screens/authentication/create_new_wallet/components/SelectDropdownComponent.tsx
src/screens/authentication/create_new_wallet/components/index.tsx
src/screens/authentication/data/data.tsx

- Add dropdown and get encryption type from "casper-storage"

[WIP] Feature: Add dropdown to choose encryption type

---

src/screens/home/HomeScreen/components/SelectAccountModal.tsx

Feature: Add edit account

---

android/app/build.gradle
ios/CasperDash.xcodeproj/project.pbxproj
ios/CasperDash/Info.plist
ios/CasperDashTests/Info.plist
package-lock.json
src/screens/authentication/create_new_wallet/InitAccountScreen/index.tsx
src/screens/home/HomeScreen/components/Account.tsx
src/screens/home/HomeScreen/components/SelectAccountModal.tsx
src/screens/settings/SettingsScreen/index.tsx
src/screens/settings/data/index.tsx
src/utils/constants/settings.ts
src/utils/helpers/account.ts
src/utils/keys.tsx

- fix setting menu on view mode
- migrate password from previous version
- performance  issue

Bugfix/fix setting menu on view mode 

---

android/app/build.gradle

Update android 32

---

src/screens/authentication/create_new_wallet/InitAccountScreen/index.tsx

loadUser is async function, in some cases the data wasn't loaded before enter the home screen, need to wait the load function finish

need to wait for load user successfully

---

android/app/build.gradle
ios/CasperDash.xcodeproj/project.pbxproj
ios/CasperDash/Info.plist
ios/CasperDashTests/Info.plist
package.json
src/screens/authentication/create_new_wallet/InitAccountScreen/index.tsx
src/screens/authentication/create_new_wallet/RecoveryPhraseScreen/index.tsx
src/screens/home/HomeScreen/components/SelectAccountModal.tsx
src/utils/constants/settings.ts
src/utils/helpers/account.ts
yarn.lock

The root cause due to missing uid when first time init account.

fix cant sign with init account

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
package.json
yarn.lock

- Fix android build (https://github.com/facebook/react-native/issues/35210)
- Fix url viewer #137 

Fix android build and url viewer

---

README.md

Update guide for linux

---

README.md

Update readme for linux

---

src/screens/staking/StakingScreen/StakingRewards/StakingRewardItem.tsx
src/screens/staking/StakingScreen/StakingRewards/index.tsx
src/services/StakingRewards/stakingRewardsApis.ts
src/services/StakingRewards/stakingRewardsType.ts
src/services/apiTypes.ts

get staking rewards from MAKE's apis

---

src/screens/home/ConfirmSendScreen/index.tsx
src/screens/home/SendScreen/index.tsx

fix transfer id

---

src/components/CAlert/index.tsx
src/components/CConfirmPinModal/index.tsx
src/screens/settings/components/DeleteAllDataButton.tsx
src/screens/staking/StakingScreen/StakingRewards/index.tsx
src/utils/config.ts
src/utils/helpers/errorHandler.ts
src/utils/hooks/useAccountInfo.ts
src/utils/hooks/useConfigurations.ts
src/utils/hooks/useDeployStatus.ts
src/utils/hooks/useNFTsInfo.ts
src/utils/hooks/usePrice.ts
src/utils/hooks/useReleaseNotes.ts
src/utils/hooks/useStakeDeploys.ts
src/utils/hooks/useTokenInfo.ts
src/utils/hooks/useValidators.ts

https://github.com/CasperDash/casperdash-mobile-wallet/issues/133

fix ui issues

---

src/screens/staking/StakingScreen/StakingForm/index.tsx
src/screens/staking/ValidatorScreen/index.tsx
src/utils/hooks/useValidators.ts

- Fix publicKey search is not working
- Improve select validator UI

Feat: #117 Improve search validator and UI

---

App.tsx
src/screens/authentication/create_new_wallet/ConnectLedgerScreen/index.tsx
src/screens/authentication/create_new_wallet/GetPublicKeyScreen/index.tsx
src/screens/authentication/create_new_wallet/components/KeyComponent.tsx
src/screens/splash_screen/SplashScreen.tsx
src/utils/constants/requestKeys.ts
src/utils/hooks/useAccountInfo.ts

Ledger - Load more account

---

src/screens/browser/components/HomePageContent/index.tsx
src/screens/home/HomeScreen/components/ViewAccountOnExplorer.tsx
src/services/Configurations/configurationApis.ts

Feat: Submit dApp content

---

App.tsx
src/navigation/ScreenProps.tsx
src/navigation/StakingNavigation/StakingRouter.ts
src/navigation/StakingNavigation/StakingScreens.ts
src/redux_manager/staking/staking_action.ts
src/redux_manager/staking/staking_reducer.ts
src/screens/staking/InfoComponent.tsx
src/screens/staking/StakingConfirmScreen/index.tsx
src/screens/staking/StakingScreen/StakedHistoryItem.tsx
src/screens/staking/StakingScreen/StakedInformationItem.tsx
src/screens/staking/StakingScreen/StakingForm/index.tsx
src/screens/staking/StakingScreen/index.tsx
src/screens/staking/UndelegateFormScreen/index.tsx
src/screens/staking/ValidatorScreen/index.tsx
src/screens/staking/components/SelectValidatorButton/index.tsx
src/screens/staking/components/ValidatorItem/index.tsx
src/screens/staking/hooks/useYupUndelegateFormSchema.ts
src/services/Configurations/configurationApis.ts
src/utils/constants/key.ts
src/utils/constants/staking.ts
src/utils/hooks/useAccountInfo.ts
src/utils/hooks/useGetFeeByEntryPoint.ts
src/utils/hooks/useStakeDeploys.ts
src/utils/selectors/staking.ts
src/utils/services/stakeServices.ts

Note:
- Update configuration for API: CSPR_AUCTION_REDELEGATE_FEE, DISABLE_INCREASE_STAKE, ENABLE_REDELEGATE

Feat: Staking with redelegate flow

---

package.json
src/screens/simple_web_view/SimpleWebViewScreen/index.tsx
yarn.lock

Feat: Progress bar for simple web view

---

src/screens/home/HomeScreen/components/Account.tsx
src/screens/home/HomeScreen/index.tsx

Fix: Space on android mobile

---

src/redux_manager/browser/browser_reducer.ts

- Add reducer main type to trigger when user clearing all state

Fix: Clear browser redux state when user clearing all data

---

src/screens/staking/StakingScreen/StakedInformationItem.tsx
src/screens/staking/UndelegateFormScreen/index.tsx
src/screens/staking/hooks/useYupUndelegateFormSchema.ts

- Fix error parsing string to number with number type
- Fix error display number undelegating format

Fix: Can not Undelegate with floating staked amount

---

src/screens/staking/StakingConfirmScreen/index.tsx

Fix: Double confirm click to undelegate amount

---

src/screens/browser/hooks/useDisconnectWithAccount.ts

- Type error for connected sites object

Fix: Type error for connected sites object

---

src/screens/staking/UndelegateFormScreen/index.tsx
src/screens/staking/hooks/useYupUndelegateFormSchema.ts

Fix: Validate maximum amount stake

---

src/screens/browser/components/HomePageContent/index.tsx

Fix: Typo ui break on submit link

---

src/screens/nft/NFTDetailScreen.tsx

- Add token ID on NFT Detail page

Feat: #167 NFT token ID

---

src/utils/constants/key.ts
src/utils/hooks/useStakeDeploys.ts

- Check the redelegating status and update it
-   [ ] I removed all comments or unnecessary code.

Fix: Update redelegating status

---

src/screens/nft/NFTDetailScreen/TransferNFTForm.tsx
src/services/NFT/nftApis.ts

Feat: Load fee transfer NFT
